### ISSUE TITLE
ADS Issue ?

### ISSUE THREAD

**Issue by scafroglia93** [ricklahaye/securedns.eu-config#2]
Some advertisements are not filtered though, present in the adblock via github

**Comment by ricklahaye** [comment]
Should be fixed now. Block list is updated automatically daily

**Comment by beerisgood** [comment]
I got Google ads:
https://www.deskmodder.de/blog/2020/03/20/windows-10-20h2-die-systemsteuerung-wird-weiter-kastriert/

![Screenshot_20200320-131526](https://user-images.githubusercontent.com/9625159/77162733-e65d1300-6aac-11ea-9006-07f2a47047ab.png)
