### ISSUE TITLE
OpenNIC TLD does not seem to work

### ISSUE THREAD

**Issue by hippi-viking** [ricklahaye/securedns.eu-config#3]
Hi Rick,

There is a bulletpoint on securedns.eu stating that OpenNIC (and Namecoin) TLDs are resolved by your server. However I do not seem to be able to resolve those TLDs without manual overrides to an OpenNIC server.
Are those bulletpoints left-overs from a previous config, do you plan to resolve those domains in the future or are they missing from the current config by mistake?

Cheers.

**Comment by ricklahaye** [comment]
Bit late, but can you try again? Should be fixed. @hippi-viking 

You can use followign for tests:
- test.bazar
- grep.geek

**Comment by hippi-viking** [comment]
No worries. :)
I confirm it does work great now, thank you.
